# Generated by Django 4.2.5 on 2023-09-19 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_uuid', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('check_status', models.IntegerField(default=0)),
                ('uploader_comment', models.TextField(blank=True)),
                ('check_comment', models.TextField(blank=True)),
                ('check_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_image_contents', to=settings.AUTH_USER_MODEL)),
                ('upload_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_contents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
