# Generated by Django 4.2.5 on 2023-09-21 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('check_status', models.IntegerField(default=0)),
                ('uploader_comment', models.TextField(blank=True)),
                ('check_comment', models.TextField(blank=True)),
                ('detect_result', models.TextField(blank=True)),
                ('check_date', models.DateTimeField(blank=True)),
                ('check_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_image_contents', to=settings.AUTH_USER_MODEL)),
                ('upload_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_contents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
